// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_runner_setup.sql

package sqlc

import (
	"context"
)

const getProjectRunnerSetupHash = `-- name: GetProjectRunnerSetupHash :one
SELECT content_hash FROM project_runner_setup WHERE runner_id = ? AND project_id = ?
`

type GetProjectRunnerSetupHashParams struct {
	RunnerID  string `json:"runner_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetProjectRunnerSetupHash(ctx context.Context, arg GetProjectRunnerSetupHashParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getProjectRunnerSetupHash, arg.RunnerID, arg.ProjectID)
	var content_hash string
	err := row.Scan(&content_hash)
	return content_hash, err
}

const setProjectRunnerSetupHash = `-- name: SetProjectRunnerSetupHash :exec
INSERT INTO project_runner_setup (runner_id, project_id, content_hash) VALUES (?, ?, ?)
ON CONFLICT (runner_id, project_id) DO UPDATE SET content_hash = excluded.content_hash
`

type SetProjectRunnerSetupHashParams struct {
	RunnerID    string `json:"runner_id"`
	ProjectID   string `json:"project_id"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) SetProjectRunnerSetupHash(ctx context.Context, arg SetProjectRunnerSetupHashParams) error {
	_, err := q.db.ExecContext(ctx, setProjectRunnerSetupHash, arg.RunnerID, arg.ProjectID, arg.ContentHash)
	return err
}
