// The shared contract fixtures.
//
// Every file in `src/contracts/fixtures/` is a realistic wire payload for one
// resource in `docs/conversation/decisions.md` §5. This table binds each file
// to the schema that must decode it. The Go implementation is expected to
// decode the same files, so the directory is a stable cross-language contract
// surface: add a fixture here and the Go test picks it up by name.
import * as Schema from "effect/Schema";

import {
  AccountBootstrap,
  BillingReport,
  CheckoutResponse,
  CreateOrganizationResponse,
  FleetResponse,
  Invitation,
  Member,
  MembersResponse,
  NextResponse,
  Onboarding,
  OnboardingProgress,
  PlanReport,
  PolicyApproval,
  ProjectIntegration,
  ProjectsResponse,
  RunnerEnrollment,
  SupportResponse,
  UpdatesReport,
} from "./account.ts";

import {
  AttemptDiff,
  AttemptPage,
  ChangeDetail,
  ChangeRequestList,
  CommentPage,
  CreateIssueRequest,
  HistoryPage,
  NativeError,
  NativeIssue,
  NativeProject,
  TransitionRequest,
  UpdateIssueRequest,
  WorkItemPage,
} from "./work.ts";
import {
  Bootstrap,
  Command,
  Conversation,
  ConversationEvent,
  ConversationListResponse,
  ConversationSnapshot,
  CreateConversationRequest,
  CreateConversationResponse,
  ApiError,
  Execution,
  LinkRequest,
  LinkResponse,
  Message,
  MessagePageResponse,
  Question,
  Receipt,
} from "./conversation.ts";
import { UsageReport } from "./usage.ts";

/** Any schema that decodes from JSON with no services. */
export type FixtureSchema = Schema.Codec<any, any, never, never>;

export const FIXTURE_SCHEMAS: Readonly<Record<string, FixtureSchema>> = {
  "account-billing.json": BillingReport,
  "account-bootstrap.json": AccountBootstrap,
  "account-bootstrap-support.json": AccountBootstrap,
  "account-checkout.json": CheckoutResponse,
  "account-fleet.json": FleetResponse,
  "account-fleet-empty.json": FleetResponse,
  "account-integration.json": ProjectIntegration,
  "account-invitation.json": Invitation,
  "account-member.json": Member,
  "account-members.json": MembersResponse,
  "account-next.json": NextResponse,
  "account-onboarding.json": Onboarding,
  "account-onboarding-progress.json": OnboardingProgress,
  "account-organization-created.json": CreateOrganizationResponse,
  "account-plan.json": PlanReport,
  "account-policy.json": PolicyApproval,
  "account-projects.json": ProjectsResponse,
  "account-runner-enrollment.json": RunnerEnrollment,
  "account-support.json": SupportResponse,
  "account-updates.json": UpdatesReport,
  "bootstrap.json": Bootstrap,
  "command-answer.json": Command,
  "command-cancel.json": Command,
  "command-continue.json": Command,
  "command-interrupt.json": Command,
  "command-message.json": Command,
  "command-retry.json": Command,
  "conversation-list.json": ConversationListResponse,
  "conversation-private.json": Conversation,
  "conversation-snapshot.json": ConversationSnapshot,
  "conversation.json": Conversation,
  "create-conversation.json": CreateConversationResponse,
  "create-conversation-request.json": CreateConversationRequest,
  "error.json": ApiError,
  "error-stale-execution.json": ApiError,
  "event-closed.json": ConversationEvent,
  "event-conversation-updated.json": ConversationEvent,
  "event-heartbeat.json": ConversationEvent,
  "event-message-delta.json": ConversationEvent,
  "execution.json": Execution,
  "link-request.json": LinkRequest,
  "link-response.json": LinkResponse,
  "message-assistant.json": Message,
  "message-attention.json": Message,
  "message-issue.json": Message,
  "message-page.json": MessagePageResponse,
  "message-proposal.json": Message,
  "message-status.json": Message,
  "message-user.json": Message,
  "question-answered.json": Question,
  "question-multiple.json": Question,
  "question.json": Question,
  "receipt-unknown.json": Receipt,
  "receipt.json": Receipt,
  "usage-24h.json": UsageReport,
  "usage-30d.json": UsageReport,
  "usage-empty.json": UsageReport,
  "work-attempt-diff.json": AttemptDiff,
  "work-attempt-list.json": AttemptPage,
  "work-change-detail.json": ChangeDetail,
  "work-change-list.json": ChangeRequestList,
  "work-comment-list.json": CommentPage,
  "work-error-conflict.json": NativeError,
  "work-history.json": HistoryPage,
  "work-item-create-request.json": CreateIssueRequest,
  "work-item-list.json": WorkItemPage,
  "work-item-patch-request.json": UpdateIssueRequest,
  "work-item.json": NativeIssue,
  "work-project.json": NativeProject,
  "work-transition-request.json": TransitionRequest,
};

export const FIXTURE_DIRECTORY = "src/contracts/fixtures";
